#!/usr/bin/env node

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';

import { handleAnalyzeTask } from './handlers/analyze-task.js';
import { handleDebugWorkflow } from './handlers/debug-workflow.js';
import { handleExecuteClaudeScript } from './handlers/execute-claude-script.js';

class BioinformaticsMCPServer {
  private server: Server;
  private projectPath: string;

  constructor() {
    this.projectPath = process.env.PROJECT_PATH || './test';
    this.server = new Server(
      {
        name: 'bioinformatics-workflow-server',
        version: '2.1.0',
      },
      {
        capabilities: {
          tools: {},
        },
      }
    );

    this.setupHandlers();
  }

  private setupHandlers() {
    this.server.setRequestHandler(ListToolsRequestSchema, async () => {
      return {
        tools: [
          {
            name: 'analyze_bioinformatics_task',
            description: 'Analyze user intent and create a bioinformatics workflow plan. This tool helps understand your analysis goals and prepares the workflow structure. After this, ask Claude to generate Python scripts (≤100 lines each), then use execute_claude_script to run them.',
            inputSchema: {
              type: 'object',
              properties: {
                user_request: {
                  type: 'string',
                  description: 'The user\'s bioinformatics analysis request in natural language',
                },
                data_files: {
                  type: 'array',
                  items: {
                    type: 'string',
                  },
                  description: 'List of input data file paths (e.g., ["C:\\Users\\username\\data.h5ad", "data2.csv"]). Include full file paths.',
                },
                additional_context: {
                  type: 'string',
                  description: 'Any additional context or specific requirements',
                },
              },
              required: ['user_request', 'data_files'],
            },
          },

          {
            name: 'debug_workflow',
            description: 'Analyze workflow execution results and provide debugging insights',
            inputSchema: {
              type: 'object',
              properties: {
                workflow_id: {
                  type: 'string',
                  description: 'The workflow ID to debug',
                },
                error_context: {
                  type: 'string',
                  description: 'Additional context about the error or issue',
                },
              },
              required: ['workflow_id'],
            },
          },
          {
            name: 'execute_claude_script',
            description: '🚀 MAIN TOOL: Automatically detect and execute Python scripts generated by Claude LLM for bioinformatics tasks. Features: ✅ Auto-detects Python installation ✅ Provides detailed installation guide if Python missing ✅ Auto-installs required packages (pandas, numpy, biopython, etc.) ✅ Full execution logging and error handling ✅ Script length monitoring (recommends ≤100 lines) ✅ HTML report generation with auto-browser opening',
            inputSchema: {
              type: 'object',
              properties: {
                claude_response: {
                  type: 'string',
                  description: 'The full response from Claude LLM that may contain Python scripts',
                },
                workflow_id: {
                  type: 'string',
                  description: 'Optional workflow ID to associate with this execution',
                },
                execution_context: {
                  type: 'string',
                  description: 'Context about what the script is supposed to do',
                },
              },
              required: ['claude_response'],
            },
          },
        ],
      };
    });

    this.server.setRequestHandler(CallToolRequestSchema, async (request) => {
      const { name, arguments: args } = request.params;

      try {
        console.error(`Received request for tool: ${name}`);
        console.error(`Arguments received:`, JSON.stringify(args, null, 2));
        
        switch (name) {
          case 'analyze_bioinformatics_task':
            return await handleAnalyzeTask(args, this.projectPath);

          case 'debug_workflow':
            return await handleDebugWorkflow(args, this.projectPath);
            
          case 'execute_claude_script':
            return await handleExecuteClaudeScript(args, this.projectPath);
            
          default:
            throw new Error(`Unknown tool: ${name}`);
        }
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
        const stackTrace = error instanceof Error ? error.stack : 'No stack trace available';
        console.error(`Tool execution error:`, error);
        console.error(`Stack trace:`, stackTrace);
        
        return {
          content: [
            {
              type: 'text',
              text: `Error: ${errorMessage}`,
            },
          ],
        };
      }
    });
  }

  async run() {
    const transport = new StdioServerTransport();
    await this.server.connect(transport);
    console.error('Bioinformatics MCP Server v2.1 running on stdio');
  }
}

// 启动服务器
const server = new BioinformaticsMCPServer();
server.run().catch((error) => {
  console.error('Failed to start server:', error);
  process.exit(1);
});