#!/usr/bin/env node

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';

import * as fs from 'fs';
import * as path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

class BioinformaticsMCPServer {
  private server: Server;
  private projectPath: string;

  constructor() {
    this.projectPath = process.env.PROJECT_PATH || './test';
    this.server = new Server(
      {
        name: 'bioinformatics-workflow-server',
        version: '2.0.0',
      },
      {
        capabilities: {
          tools: {},
        },
      }
    );

    this.setupHandlers();
  }

  private setupHandlers() {
    this.server.setRequestHandler(ListToolsRequestSchema, async () => {
      return {
        tools: [
          {
            name: 'analyze_bioinformatics_task',
            description: 'Analyze user intent and create a bioinformatics workflow plan. This tool helps understand your analysis goals and prepares the workflow structure. After this, ask Claude to generate Python scripts, then use execute_claude_script to run them.',
            inputSchema: {
              type: 'object',
              properties: {
                user_request: {
                  type: 'string',
                  description: 'The user\'s bioinformatics analysis request in natural language',
                },
                data_files: {
                  type: 'array',
                  items: {
                    type: 'string',
                  },
                  description: 'List of input data file paths (e.g., ["C:\\Users\\username\\data.h5ad", "data2.csv"]). Include full file paths.',
                },
                additional_context: {
                  type: 'string',
                  description: 'Any additional context or specific requirements',
                },
              },
              required: ['user_request', 'data_files'],
            },
          },

          {
            name: 'debug_workflow',
            description: 'Analyze workflow execution results and provide debugging insights',
            inputSchema: {
              type: 'object',
              properties: {
                workflow_id: {
                  type: 'string',
                  description: 'The workflow ID to debug',
                },
                error_context: {
                  type: 'string',
                  description: 'Additional context about the error or issue',
                },
              },
              required: ['workflow_id'],
            },
          },
          {
            name: 'execute_claude_script',
            description: '🚀 MAIN TOOL: Automatically detect and execute Python scripts generated by Claude LLM for bioinformatics tasks. Features: ✅ Auto-detects Python installation ✅ Provides detailed installation guide if Python missing ✅ Auto-installs required packages (pandas, numpy, biopython, etc.) ✅ Full execution logging and error handling',
            inputSchema: {
              type: 'object',
              properties: {
                claude_response: {
                  type: 'string',
                  description: 'The full response from Claude LLM that may contain Python scripts',
                },
                workflow_id: {
                  type: 'string',
                  description: 'Optional workflow ID to associate with this execution',
                },
                execution_context: {
                  type: 'string',
                  description: 'Context about what the script is supposed to do',
                },
              },
              required: ['claude_response'],
            },
          },
        ],
      };
    });

    this.server.setRequestHandler(CallToolRequestSchema, async (request) => {
      const { name, arguments: args } = request.params;

      try {
        console.error(`Received request for tool: ${name}`);
        console.error(`Arguments received:`, JSON.stringify(args, null, 2));
        
        switch (name) {
          case 'analyze_bioinformatics_task':
            return await this.handleAnalyzeTask(args);

          case 'debug_workflow':
            return await this.handleDebugWorkflow(args);
          case 'execute_claude_script':
            return await this.handleExecuteClaudeScript(args);
          default:
            throw new Error(`Unknown tool: ${name}`);
        }
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
        const stackTrace = error instanceof Error ? error.stack : 'No stack trace available';
        console.error(`Tool execution error:`, error);
        console.error(`Stack trace:`, stackTrace);
        
        return {
          content: [
            {
              type: 'text',
              text: `Error: ${errorMessage}`,
            },
          ],
        };
      }
    });
  }

  private async handleAnalyzeTask(args: any) {
    // 安全地处理参数，确保默认值
    const safeArgs = args || {};
    const user_request = safeArgs.user_request || '';
    const data_files = Array.isArray(safeArgs.data_files) ? safeArgs.data_files : [];
    const additional_context = safeArgs.additional_context || '';
    const workflowId = this.generateId();
    
    try {
      // 验证必需参数
      if (!user_request || user_request.trim() === '') {
        throw new Error('user_request is required and cannot be empty');
      }
      
      console.error(`Analyzing bioinformatics task: ${user_request}`);
      console.error(`Data files: ${data_files.length} files`);
      console.error(`Additional context: ${additional_context}`);
      
      // 创建工作流目录
      const workflowDir = path.join(this.projectPath, workflowId);
      fs.mkdirSync(workflowDir, { recursive: true });
      
      // 生成详细的分析计划和脚本
      console.error(`Creating analysis prompt...`);
      const analysisPrompt = this.createAnalysisPrompt(user_request, data_files, additional_context, workflowId);
      console.error(`Analysis prompt created successfully`);
      
      // 保存分析请求信息
      console.error(`Creating workflow info object...`);
      const workflowInfo = {
        id: workflowId,
        user_request,
        data_files,
        additional_context,
        created_at: new Date().toISOString(),
        status: 'planned',
        workflow_dir: workflowDir
      };
      
      console.error(`Saving workflow info to JSON...`);
      try {
        fs.writeFileSync(
          path.join(workflowDir, 'workflow_info.json'),
          JSON.stringify(workflowInfo, null, 2)
        );
        console.error(`Workflow info saved successfully`);
      } catch (jsonError) {
        console.error(`JSON stringify error:`, jsonError);
        throw jsonError;
      }

      return {
        content: [
          {
            type: 'text',
            text: `# 生物信息学工作流分析完成

## 工作流ID: ${workflowId}

## 用户请求分析:
${user_request}

## 数据文件:
${data_files.length > 0 ? data_files.map((file: string, idx: number) => `${idx + 1}. ${file}`).join('\n') : '无数据文件'}

## 分析计划:
基于您的请求，我已经创建了一个完整的生物信息学工作流。

**下一步操作:**
1. 请让Claude生成具体的Python分析脚本
2. 使用 \`execute_claude_script\` 工具自动执行生成的脚本
3. 如果遇到问题，使用 \`debug_workflow\` 工具进行调试

## 工作流目录:
${workflowDir}

## Claude LLM 分析提示:
${analysisPrompt}

**请告诉我您希望如何处理这个工作流 - 是立即执行还是需要先查看具体的分析步骤？**`,
          },
        ],
      };
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
      console.error(`Task analysis error: ${errorMessage}`);
      throw new Error(`Failed to analyze task: ${errorMessage}`);
    }
  }

  private async handleDebugWorkflow(args: any) {
    const safeArgs = args || {};
    const workflow_id = safeArgs.workflow_id || '';
    const error_context = safeArgs.error_context || '';
    
    if (!workflow_id || workflow_id.trim() === '') {
      throw new Error('workflow_id is required and cannot be empty');
    }
    
    try {
      const workflowDir = path.join(this.projectPath, workflow_id);
      const workflowInfoPath = path.join(workflowDir, 'workflow_info.json');
      const executionResultPath = path.join(workflowDir, 'execution_result.json');
      
      if (!fs.existsSync(workflowInfoPath)) {
        throw new Error(`Workflow ${workflow_id} not found`);
      }
      
      const workflowInfo = JSON.parse(fs.readFileSync(workflowInfoPath, 'utf8'));
      let executionResult = null;
      
      if (fs.existsSync(executionResultPath)) {
        executionResult = JSON.parse(fs.readFileSync(executionResultPath, 'utf8'));
      }
      
      // 收集所有相关文件信息
      const debugInfo = {
        workflow_info: workflowInfo,
        execution_result: executionResult,
        error_context,
        workflow_files: this.listWorkflowFiles(workflowDir)
      };
      
      return {
        content: [
          {
            type: 'text',
            text: `# 工作流调试报告

## 工作流ID: ${workflow_id}

## 原始请求:
${workflowInfo.user_request}

## 执行状态:
${executionResult ? executionResult.status : 'Not executed yet'}

## 错误分析:
${this.analyzeErrors(executionResult, error_context)}

## 建议解决方案:
${this.generateSuggestions(workflowInfo, executionResult)}

## 工作流文件:
${debugInfo.workflow_files.map(file => `- ${file}`).join('\n')}

## 详细调试信息:
\`\`\`json
${JSON.stringify(debugInfo, null, 2)}
\`\`\`

**请根据以上分析信息告诉Claude LLM具体的问题，我可以帮助生成修复方案或重新设计工作流。**`,
          },
        ],
      };
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
      console.error(`Workflow debug error: ${errorMessage}`);
      throw new Error(`Failed to debug workflow: ${errorMessage}`);
    }
  }

  private async handleExecuteClaudeScript(args: any) {
    const safeArgs = args || {};
    const claude_response = safeArgs.claude_response || '';
    const workflow_id = safeArgs.workflow_id || this.generateId();
    const execution_context = safeArgs.execution_context || '';
    
    if (!claude_response || claude_response.trim() === '') {
      throw new Error('claude_response is required and cannot be empty');
    }
    
    try {
      console.error(`Analyzing Claude response for Python scripts...`);
      console.error(`Response length: ${claude_response.length} characters`);
      
      // 检测和提取Python脚本
      const pythonScripts = this.extractPythonScripts(claude_response);
      
      if (pythonScripts.length === 0) {
        return {
          content: [
            {
              type: 'text',
              text: `# Claude脚本执行结果

## 检测结果: 未发现Python脚本

在Claude的响应中没有检测到可执行的Python代码块。

**提示**: 确保Python代码被包含在 \`\`\`python 代码块中。`,
            },
          ],
        };
      }

      // 创建执行目录
      const executionDir = path.join(this.projectPath, workflow_id);
      fs.mkdirSync(executionDir, { recursive: true });
      
      // 调试：保存原始响应到文件
      fs.writeFileSync(
        path.join(executionDir, 'debug_claude_response.txt'),
        claude_response,
        'utf8'
      );
      
      const executionResults = [];
      let pythonCommand: string;
      
      try {
        // 检测可用的Python命令
        pythonCommand = await this.detectPythonCommand();
        console.error(`Python检测成功: ${pythonCommand}`);
      } catch (pythonError: any) {
        // Python未安装，返回安装指导
        return {
          content: [
            {
              type: 'text',
              text: `# ❌ Python环境检测失败

${pythonError.message}

**请按照上述指导安装Python后重新运行脚本。**

## 检测到的脚本信息:
- 发现 **${pythonScripts.length}** 个Python脚本
- 需要的包: ${Array.from(new Set(pythonScripts.flatMap(s => s.dependencies))).join(', ') || '无特殊依赖'}

安装Python后，这些脚本将自动执行！`,
            },
          ],
        };
      }
      
      // 收集所有脚本的依赖包
      const allDependencies = Array.from(new Set(pythonScripts.flatMap(script => script.dependencies)));
      
      // 安装依赖包
      const packageInstallResult = await this.installPythonPackages(pythonCommand, allDependencies, executionDir);
      
      for (let i = 0; i < pythonScripts.length; i++) {
        const script = pythonScripts[i];
        const scriptName = `claude_script_${i + 1}.py`;
        const scriptPath = path.join(executionDir, scriptName);
        
        // 保存脚本文件 (使用UTF-8编码)
        fs.writeFileSync(scriptPath, script.code, 'utf8');
        
        console.error(`Executing Python script ${i + 1}/${pythonScripts.length}`);
        
        try {
          // 执行Python脚本 (Windows)
          const pythonCmd = `${this.buildCdCommand(executionDir)} && ${pythonCommand} "${scriptName}"`;
          
          console.error(`Executing command: ${pythonCmd}`);
          
          const { stdout, stderr } = await execAsync(pythonCmd, {
            timeout: 300000, // 5分钟超时
            encoding: 'utf8',
            ...this.getShellConfig()
          });
          
          executionResults.push({
            script_number: i + 1,
            script_name: scriptName,
            description: script.description,
            dependencies: script.dependencies,
            status: 'success',
            stdout,
            stderr,
            execution_time: new Date().toISOString()
          });
          
        } catch (execError: any) {
          executionResults.push({
            script_number: i + 1,
            script_name: scriptName,
            description: script.description,
            dependencies: script.dependencies,
            status: 'error',
            stdout: execError.stdout || '',
            stderr: execError.stderr || execError.message,
            execution_time: new Date().toISOString()
          });
        }
      }
      
      // 保存执行结果
      const fullResult = {
        workflow_id,
        execution_context,
        claude_response: claude_response.substring(0, 1000) + '...', // 截断长响应
        scripts_found: pythonScripts.length,
        dependencies_detected: allDependencies,
        package_installation: packageInstallResult,
        execution_results: executionResults,
        executed_at: new Date().toISOString()
      };
      
      fs.writeFileSync(
        path.join(executionDir, 'claude_script_results.json'),
        JSON.stringify(fullResult, null, 2)
      );
      
      // 生成报告
      const successCount = executionResults.filter(r => r.status === 'success').length;
      const errorCount = executionResults.filter(r => r.status === 'error').length;
      
      return {
        content: [
          {
            type: 'text',
            text: `# Claude Python脚本执行报告

## 工作流ID: ${workflow_id}

## 执行概况:
- 检测到 **${pythonScripts.length}** 个Python脚本
- 成功执行: **${successCount}** 个
- 执行失败: **${errorCount}** 个

## Python环境:
- Python命令: \`${pythonCommand}\`
- 检测到的依赖包: ${allDependencies.length > 0 ? allDependencies.join(', ') : '无特殊依赖'}

## 包安装结果:
${packageInstallResult.logs.map(log => `- ${log}`).join('\n')}

## 执行上下文:
${execution_context}

## 详细结果:

${executionResults.map((result, idx) => `
### 脚本 ${result.script_number}: ${result.script_name}
**状态**: ${result.status === 'success' ? '✅ 成功' : '❌ 失败'}
**描述**: ${result.description}
**依赖包**: ${result.dependencies.length > 0 ? result.dependencies.join(', ') : '无特殊依赖'}

**标准输出**:
\`\`\`
${result.stdout || '(无输出)'}
\`\`\`

**错误输出**:
\`\`\`
${result.stderr || '(无错误)'}
\`\`\`
`).join('\n')}

## 执行目录:
${executionDir}

${errorCount > 0 ? 
`## ⚠️ 发现错误
有 ${errorCount} 个脚本执行失败，请检查错误信息并考虑：
1. 检查Python环境和依赖包安装状态
2. 验证输入数据和文件路径
3. 检查脚本逻辑和语法
4. 使用 \`debug_workflow\` 工具进行详细分析

${!packageInstallResult.success ? '⚠️ 部分Python包安装失败，这可能是导致脚本执行失败的原因。' : ''}` :
`## 🎉 执行成功
所有脚本都成功执行！你可以查看执行目录中的结果文件。`}

**下次如果Claude生成新的脚本，我会自动检测依赖并安装，然后执行它们！**`,
          },
        ],
      };
      
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
      console.error(`Claude script execution error: ${errorMessage}`);
      throw new Error(`Failed to execute Claude scripts: ${errorMessage}`);
    }
  }

  private generateId(): string {
    return `bio_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
  }

  private getShellConfig() {
    return {
      shell: 'cmd.exe'
    };
  }

  private buildCdCommand(directory: string): string {
    return `cd /d "${directory}"`;
  }

  private async detectPythonCommand(): Promise<string> {
    const pythonCommands = ['python', 'python3', 'py'];
    
    for (const cmd of pythonCommands) {
      try {
        const { stdout } = await execAsync(`${cmd} --version`, {
          timeout: 5000,
          ...this.getShellConfig()
        });
        if (stdout) {
          console.error(`Found Python: ${cmd} - ${stdout.trim()}`);
          return cmd;
        }
      } catch (error) {
        console.error(`${cmd} not available: ${error instanceof Error ? error.message : error}`);
      }
    }
    
    // 如果都不可用，尝试常见的Windows Python安装路径
    const fullPaths = [
      'C:\\Python39\\python.exe',
      'C:\\Python38\\python.exe',
      'C:\\Python310\\python.exe',
      'C:\\Python311\\python.exe',
      'C:\\Python312\\python.exe',
      'C:\\Users\\%USERNAME%\\AppData\\Local\\Programs\\Python\\Python39\\python.exe',
      'C:\\Users\\%USERNAME%\\AppData\\Local\\Programs\\Python\\Python310\\python.exe',
      'C:\\Users\\%USERNAME%\\AppData\\Local\\Programs\\Python\\Python311\\python.exe',
      'C:\\Users\\%USERNAME%\\AppData\\Local\\Programs\\Python\\Python312\\python.exe'
    ];
    
    for (const fullPath of fullPaths) {
      try {
        const { stdout } = await execAsync(`"${fullPath}" --version`, {
          timeout: 5000,
          ...this.getShellConfig()
        });
        if (stdout) {
          console.error(`Found Python at full path: ${fullPath} - ${stdout.trim()}`);
          return `"${fullPath}"`;
        }
      } catch (error) {
        // 继续尝试下一个路径
      }
    }
    
    // 生成详细的Python安装指导
    const installationGuide = this.generatePythonInstallationGuide();
    throw new Error(`未找到Python解释器！\n\n${installationGuide}`);
  }

  private generatePythonInstallationGuide(): string {
    return `🐍 Python安装指导

请按照以下步骤安装Python：

## 方法1: 从官网下载（推荐）
1. 访问 https://www.python.org/downloads/
2. 下载最新版本的Python (建议Python 3.9或更高版本)
3. 运行安装程序时，**务必勾选 "Add Python to PATH"**
4. 选择 "Install Now" 进行默认安装

## 方法2: 使用Microsoft Store（Windows 10/11）
1. 打开Microsoft Store
2. 搜索 "Python"
3. 安装 "Python 3.11" 或更新版本

## 方法3: 使用包管理器
- **Chocolatey**: choco install python
- **Scoop**: scoop install python
- **winget**: winget install Python.Python.3

## 安装完成后验证：
打开命令提示符(cmd)或PowerShell，输入以下命令：
\`\`\`
python --version
\`\`\`
或
\`\`\`
py --version
\`\`\`

如果显示Python版本信息，说明安装成功！

## 常见问题：
- 如果提示"python不是内部或外部命令"，请重启命令提示符或重新安装时勾选"Add to PATH"
- 推荐安装Python 3.9+版本以获得最佳兼容性

安装完成后，请重新运行您的生物信息学分析任务。`;
  }

  private extractDependencies(code: string): string[] {
    const dependencies = new Set<string>();
    
    // 匹配 import 语句
    const importRegex = /^(?:from\s+(\S+)|import\s+(\S+))/gm;
    let match;
    
    while ((match = importRegex.exec(code)) !== null) {
      const packageName = match[1] || match[2];
      if (packageName) {
        // 提取主包名（去掉子模块）
        const mainPackage = packageName.split('.')[0];
        
        // 映射常见的包名到pip包名（只映射不同名的包）
        const packageMapping: { [key: string]: string } = {
          'Bio': 'biopython',
          'cv2': 'opencv-python',
          'sklearn': 'scikit-learn',
          'PIL': 'Pillow',
          'skimage': 'scikit-image'
        };
        
        const pipPackage = packageMapping[mainPackage] || mainPackage;
        
        // 只添加非标准库的包
        if (!this.isStandardLibrary(mainPackage)) {
          dependencies.add(pipPackage);
        }
      }
    }
    
    return Array.from(dependencies);
  }

  private isStandardLibrary(packageName: string): boolean {
    const standardLibraries = [
      'os', 'sys', 'json', 'csv', 'sqlite3', 'datetime', 'time', 'random',
      'math', 'statistics', 'collections', 'itertools', 'functools', 'operator',
      'pathlib', 'glob', 'shutil', 'tempfile', 'zipfile', 'tarfile',
      'urllib', 'http', 'email', 'html', 'xml', 'pickle', 'copy',
      'threading', 'multiprocessing', 'subprocess', 'argparse', 'logging',
      'unittest', 're', 'string', 'textwrap', 'unicodedata', 'struct',
      'codecs', 'io', 'base64', 'binascii', 'hashlib', 'hmac', 'secrets'
    ];
    
    return standardLibraries.includes(packageName);
  }

  private async installPythonPackages(pythonCommand: string, packages: string[], executionDir: string): Promise<{success: boolean, logs: string[]}> {
    const logs: string[] = [];
    let allSuccess = true;
    
    if (packages.length === 0) {
      logs.push('📦 无需安装额外的Python包');
      return { success: true, logs };
    }
    
    logs.push(`📦 开始安装Python包: ${packages.join(', ')}`);
    
    for (const pkg of packages) {
      try {
        logs.push(`🔄 正在安装 ${pkg}...`);
        
        const installCmd = `${this.buildCdCommand(executionDir)} && ${pythonCommand} -m pip install ${pkg} --quiet --no-warn-script-location`;
        
        const { stdout, stderr } = await execAsync(installCmd, {
          timeout: 120000, // 2分钟超时
          encoding: 'utf8',
          ...this.getShellConfig()
        });
        
        if (stderr && !stderr.includes('WARNING') && !stderr.includes('already satisfied')) {
          logs.push(`⚠️ ${pkg} 安装时有警告: ${stderr.trim()}`);
        } else {
          logs.push(`✅ ${pkg} 安装成功`);
        }
        
      } catch (error: any) {
        const errorMsg = error.stderr || error.message || '未知错误';
        logs.push(`❌ ${pkg} 安装失败: ${errorMsg}`);
        
        // 尝试升级pip并重试
        if (errorMsg.includes('pip') || errorMsg.includes('setuptools')) {
          try {
            logs.push(`🔄 尝试升级pip并重新安装 ${pkg}...`);
            const upgradeCmd = `${this.buildCdCommand(executionDir)} && ${pythonCommand} -m pip install --upgrade pip setuptools wheel`;
            
            await execAsync(upgradeCmd, { timeout: 60000, ...this.getShellConfig() });
            
            const retryCmd = `${this.buildCdCommand(executionDir)} && ${pythonCommand} -m pip install ${pkg} --quiet`;
            
            await execAsync(retryCmd, { timeout: 120000, ...this.getShellConfig() });
            logs.push(`✅ ${pkg} 重试安装成功`);
            // 重试成功，不设置allSuccess = false
            
          } catch (retryError) {
            logs.push(`❌ ${pkg} 重试安装仍然失败`);
            allSuccess = false;
          }
        } else {
          allSuccess = false;
        }
      }
    }
    
    return { success: allSuccess, logs };
  }

  private extractPythonScripts(text: string): Array<{code: string, description: string, dependencies: string[]}> {
    const scripts: Array<{code: string, description: string, dependencies: string[]}> = [];
    
    // 匹配 ```python 代码块
    const pythonCodeBlockRegex = /```python\n([\s\S]*?)```/g;
    let match;
    
    while ((match = pythonCodeBlockRegex.exec(text)) !== null) {
      const code = match[1].trim();
      
      // 跳过空代码块或过短的代码块
      if (code.length < 10) continue;
      
      // 检查是否是生物信息学相关的代码
      if (this.isBioinformaticsScript(code)) {
        // 尝试提取代码前的描述
        const beforeCode = text.substring(0, match.index);
        const description = this.extractScriptDescription(beforeCode);
        
        // 提取依赖包
        const dependencies = this.extractDependencies(code);
        
        scripts.push({
          code,
          description: description || '自动检测的Python脚本',
          dependencies
        });
      }
    }
    
    // 也尝试匹配没有语言标识的代码块，但包含生物信息学关键词
    const genericCodeBlockRegex = /```\n([\s\S]*?)```/g;
    while ((match = genericCodeBlockRegex.exec(text)) !== null) {
      const code = match[1].trim();
      
      if (code.length < 10) continue;
      
      // 检查是否看起来像Python代码且与生物信息学相关
      if (this.looksLikePython(code) && this.isBioinformaticsScript(code)) {
        const beforeCode = text.substring(0, match.index);
        const description = this.extractScriptDescription(beforeCode);
        
        // 避免重复添加已经通过python标签提取的代码
        const alreadyExists = scripts.some(script => 
          this.calculateSimilarity(script.code, code) > 0.8
        );
        
        if (!alreadyExists) {
          const dependencies = this.extractDependencies(code);
          scripts.push({
            code,
            description: description || '检测到的Python脚本',
            dependencies
          });
        }
      }
    }
    
    return scripts;
  }

  private isBioinformaticsScript(code: string): boolean {
    const bioKeywords = [
      // 生物信息学库
      'biopython', 'pandas', 'numpy', 'matplotlib', 'seaborn', 'scipy',
      'sklearn', 'Bio', 'pysam', 'HTSeq', 'pybedtools',
      
      // 生物信息学术语
      'fastq', 'fasta', 'vcf', 'bam', 'sam', 'bed', 'gtf', 'gff',
      'sequence', 'genome', 'gene', 'protein', 'DNA', 'RNA',
      'alignment', 'blast', 'annotation', 'expression',
      'variant', 'mutation', 'phylogeny', 'assembly',
      
      // 常见生物信息学操作
      'SeqIO', 'read_csv', 'read_table', 'plot', 'histogram',
      'scatter', 'heatmap', 'clustering', 'pca', 'differential',
      
      // 文件扩展名
      '.fastq', '.fasta', '.vcf', '.bam', '.sam', '.bed',
      '.gtf', '.gff', '.csv', '.tsv', '.txt'
    ];
    
    const codeUpper = code.toUpperCase();
    return bioKeywords.some(keyword => 
      codeUpper.includes(keyword.toUpperCase())
    );
  }

  private looksLikePython(code: string): boolean {
    const pythonIndicators = [
      'import ', 'from ', 'def ', 'class ', 'if __name__',
      'print(', '.py', 'pandas', 'numpy', '#!/usr/bin/env python'
    ];
    
    return pythonIndicators.some(indicator => 
      code.includes(indicator)
    );
  }

  private extractScriptDescription(beforeCode: string): string {
    // 提取代码块前最近的一段文字作为描述
    const lines = beforeCode.split('\n').reverse();
    const descriptionLines = [];
    
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed === '') continue;
      
      // 跳过markdown标记
      if (trimmed.startsWith('#') || trimmed.startsWith('*') || 
          trimmed.startsWith('-') || trimmed.startsWith('>')) {
        descriptionLines.unshift(trimmed);
        continue;
      }
      
      // 如果是普通文本，添加并停止
      if (trimmed.length > 10 && trimmed.length < 200) {
        descriptionLines.unshift(trimmed);
        break;
      }
    }
    
    return descriptionLines.join(' ').substring(0, 150);
  }

  private calculateSimilarity(str1: string, str2: string): number {
    // 简单的字符串相似度计算
    const longer = str1.length > str2.length ? str1 : str2;
    const shorter = str1.length > str2.length ? str2 : str1;
    
    if (longer.length === 0) return 1.0;
    
    const editDistance = this.levenshteinDistance(longer, shorter);
    return (longer.length - editDistance) / longer.length;
  }

  private levenshteinDistance(str1: string, str2: string): number {
    const matrix = [];
    
    for (let i = 0; i <= str2.length; i++) {
      matrix[i] = [i];
    }
    
    for (let j = 0; j <= str1.length; j++) {
      matrix[0][j] = j;
    }
    
    for (let i = 1; i <= str2.length; i++) {
      for (let j = 1; j <= str1.length; j++) {
        if (str2.charAt(i - 1) === str1.charAt(j - 1)) {
          matrix[i][j] = matrix[i - 1][j - 1];
        } else {
          matrix[i][j] = Math.min(
            matrix[i - 1][j - 1] + 1,
            matrix[i][j - 1] + 1,
            matrix[i - 1][j] + 1
          );
        }
      }
    }
    
    return matrix[str2.length][str1.length];
  }

  private createAnalysisPrompt(userRequest: string, dataFiles: string[], additionalContext: string, workflowId: string): string {
    // 确保参数安全
    const safeUserRequest = userRequest || '未指定分析需求';
    const safeDataFiles = Array.isArray(dataFiles) ? dataFiles : [];
    const safeAdditionalContext = additionalContext || '无';
    const safeWorkflowId = workflowId || 'unknown';
    
    return `# 生物信息学工作流分析

## 用户请求:
${safeUserRequest}

## 数据文件:
${safeDataFiles.length > 0 ? safeDataFiles.map((file, idx) => `${idx + 1}. ${file}`).join('\n') : '无数据文件'}

## 附加信息:
${safeAdditionalContext}

## 工作流ID:
${safeWorkflowId}

---

**Claude LLM，请基于以上信息：**

1. **分析用户意图** - 理解用户想要进行什么类型的生物信息学分析
2. **设计分析流程** - 创建详细的分析步骤
3. **生成具体脚本** - 为每个步骤生成可执行的命令
4. **考虑数据类型** - 根据文件类型选择合适的工具和参数

请提供：
- 详细的分析计划
- 每个步骤的具体命令
- 预期的输出文件
- 可能遇到的问题和解决方案

这将帮助我生成完整的可执行工作流。`;
  }

  private listWorkflowFiles(workflowDir: string): string[] {
    try {
      return fs.readdirSync(workflowDir, { recursive: true }).map(file => String(file));
    } catch (error) {
      return [];
    }
  }

  private analyzeErrors(executionResult: any, errorContext: string): string {
    if (!executionResult) {
      return "工作流尚未执行";
    }

    if (executionResult.status === 'success') {
      return "工作流执行成功，无错误";
    }

    let analysis = "检测到以下问题:\n";
    
    if (executionResult.stderr) {
      analysis += `\n**标准错误输出:**\n${executionResult.stderr}\n`;
    }

    if (errorContext) {
      analysis += `\n**用户提供的错误信息:**\n${errorContext}\n`;
    }

    return analysis;
  }

  private generateSuggestions(workflowInfo: any, executionResult: any): string {
    let suggestions = "建议的解决方案:\n\n";

    suggestions += "1. **检查工具安装** - 确保所需的生物信息学工具已正确安装\n";
    suggestions += "2. **验证数据文件** - 确认输入文件存在且格式正确\n";
    suggestions += "3. **检查文件路径** - 确保所有文件路径都是正确的\n";
    suggestions += "4. **查看日志文件** - 检查工作流目录中的日志文件获取更多信息\n";

    if (executionResult && executionResult.stderr) {
      suggestions += "5. **分析错误信息** - 将错误信息提供给Claude LLM进行详细分析\n";
    }

    suggestions += "\n**下一步行动:**\n";
    suggestions += "- 将详细错误信息告诉Claude LLM\n";
    suggestions += "- 请求生成修复后的工作流\n";
    suggestions += "- 考虑简化分析流程或使用替代工具\n";

    return suggestions;
  }

  async run() {
    const transport = new StdioServerTransport();
    await this.server.connect(transport);
    console.error('Bioinformatics MCP Server v2.0 running on stdio');
  }
}

// 启动服务器
const server = new BioinformaticsMCPServer();
server.run().catch((error) => {
  console.error('Failed to start server:', error);
  process.exit(1);
});